### ISSUE TITLE
Possible mispelling in transcribe.py?

### ISSUE THREAD

**Issue by ahoms** [ad-aures/mufidiwiwhi#1]
Tried to run mufidiwiwhi with cpu device  (not enough memory for cuda) and I get  this error

Traceback (most recent call last):
  File "/home/albert/.local/bin/mufidiwiwhi", line 33, in <module>
    sys.exit(load_entry_point('mufidiwiwhi', 'console_scripts', 'mufidiwiwhi')())
  File "/home/albert/mufidiwiwhi/mufidiwiwhi/transcribe.py", line 432, in cli
    result = transcribe(model, audio_dicts, temperature=temperature, **args)
  File "/home/albert/mufidiwiwhi/mufidiwiwhi/transcribe.py", line 118, in transcribe
    warnings.warn("Performing inference on CPU when CUDA is available")
NameError: name 'warnings' is not defined. Did you mean: 'Warning'?

**Comment by ahoms** [comment]
Commenting the lines overcomes the issue. Then crashes due to another error

RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

This one seems to  be also solvable https://github.com/openai/whisper/discussions/92
